apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-nfs
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: lisanas
    path: /volume1/kubernetes